# Generated by Django 4.2.29 on 2026-03-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoBordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_por_mil_pontos', models.DecimalField(decimal_places=2, help_text='Valor cobrado a cada 1.000 pontos (ex: R$ 3,50)', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Configuração de Preços do Bordado',
            },
        ),
        migrations.CreateModel(
            name='MatrizBordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('imagem_original', models.ImageField(blank=True, null=True, upload_to='logos_originais/')),
                ('arquivo_dst', models.FileField(blank=True, null=True, upload_to='matrizes_dst/')),
                ('largura_desejada_mm', models.DecimalField(decimal_places=2, default=0, help_text='Largura final desejada', max_digits=6)),
                ('cor_tecido_fundo', models.CharField(choices=[('TRANSPARENTE', 'Ignorar Fundo Transparente (PNG)'), ('Branco', 'Tecido Branco'), ('Preto', 'Tecido Preto'), ('NENHUMA', 'Bordar TUDO (Inclusive o fundo)')], default='Branco', help_text='Escolha a cor do tecido para NÃO bordar essa cor.', max_length=20)),
                ('quantidade_pontos', models.PositiveIntegerField(default=0)),
                ('pontos_por_minuto', models.PositiveIntegerField(default=900)),
                ('largura_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('altura_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sequencia_cores', models.TextField(blank=True)),
                ('mudancas_cores', models.PositiveIntegerField(default=0)),
                ('bastidor_recomendado', models.CharField(blank=True, choices=[('10x10', '10x10 cm'), ('13x18', '13x18 cm'), ('16x26', '16x26 cm')], max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, help_text='Custo base do produto (ex: R$ 30,00)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago', models.BooleanField(default=False, verbose_name='Já foi pago?')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.matrizbordado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('matriz_bordado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.matrizbordado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto')),
            ],
        ),
    ]
