# Generated by Django 4.2.29 on 2026-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaobordado',
            name='preco_por_mil_pontos',
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='valor_camisa_lisa',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='valor_mil_pontos',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
