# Generated by Django 4.2.29 on 2026-03-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_configuracaobordado_preco_por_mil_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.matrizbordado'),
        ),
    ]
