# Generated by Django 4.2.29 on 2026-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_pedido_matriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizbordado',
            name='altura_desejada_mm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
