# Generated by Django 4.2.29 on 2026-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_matrizbordado_altura_desejada_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrizbordado',
            name='arquivo_dst',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='matriz',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='bastidor_recomendado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='cor_tecido_fundo',
            field=models.CharField(choices=[('TRANSPARENTE', 'Ignorar Fundo Transparente (PNG)'), ('Branco', 'Tecido Branco'), ('Preto', 'Tecido Preto'), ('NENHUMA', 'Bordar TUDO')], default='Branco', max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='largura_desejada_mm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='pontos_por_minuto',
            field=models.PositiveIntegerField(default=850),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
