# Generated by Django 4.2.29 on 2026-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_remove_matrizbordado_arquivo_dst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizbordado',
            name='densidade_escolhida',
            field=models.DecimalField(decimal_places=1, default=5.5, max_digits=3),
        ),
    ]
