# Generated by Django 4.2.29 on 2026-03-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_matrizbordado_densidade_escolhida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('camiseta', 'Camiseta'), ('camisa', 'Camisa'), ('bone', 'Boné'), ('calca', 'Calça'), ('jaqueta', 'Jaqueta'), ('toalha', 'Toalha'), ('outro', 'Outro')], default='camiseta', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='valor_camisa_lisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.produto'),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='cor_tecido_fundo',
            field=models.CharField(choices=[('TRANSPARENTE', 'Ignorar Fundo Transparente (PNG)'), ('Branco', 'Tecido Branco'), ('Preto', 'Tecido Preto'), ('NENHUMA', 'Bordar TUDO'), ('AUTO', 'Detecção Automática')], default='AUTO', max_length=20),
        ),
    ]
