# Generated by Django 4.2.29 on 2026-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_produto_options_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizbordado',
            name='arquivo_matriz',
            field=models.FileField(blank=True, help_text='Arquivo de bordado para a máquina (.dst, .pes, .exp, .jef…)', null=True, upload_to='arquivos_matrizes/'),
        ),
        migrations.AddField(
            model_name='matrizbordado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
