# Generated by Django 4.2.29 on 2026-03-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_matrizbordado_arquivo_matriz_matrizbordado_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('insumos', 'Insumos / Materiais'), ('fornecedor', 'Fornecedor'), ('imposto', 'Imposto / Taxa'), ('salario', 'Salário / Funcionário'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('observacoes', models.TextField(blank=True)),
                ('notificacao_enviada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria', 'nome']},
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='dias_aviso_conta',
            field=models.PositiveIntegerField(default=3, help_text='Quantos dias antes do vencimento enviar o aviso'),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='email_destinatario',
            field=models.EmailField(blank=True, help_text='Email que vai receber os alertas (pode ser o mesmo do remetente)', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='email_remetente',
            field=models.EmailField(blank=True, help_text='Seu Gmail que vai enviar os alertas. Ex: seuemail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='email_senha_app',
            field=models.CharField(blank=True, help_text='Senha de App do Gmail (16 caracteres, gerada em myaccount.google.com/apppasswords)', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrizbordado',
            name='arquivo_matriz',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_matrizes/'),
        ),
    ]
