# Generated by Django 4.2.29 on 2026-03-20 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0009_contapagar_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaobordado',
            name='dias_aviso_conta',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='email_destinatario',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='email_remetente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='email_senha_app',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(blank=True, help_text='Nome exibido no sistema', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.TextField(blank=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
