# Generated by Django 4.2.29 on 2026-03-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_configuracaobordado_dias_aviso_conta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_produto',
            field=models.CharField(blank=True, help_text='Material, composição ou detalhes do produto. Ex: 100% Algodão, 30.1 fios', max_length=300),
        ),
    ]
