# Generated by Django 4.2.29 on 2026-03-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_produto_options_produto_descricao_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('categoria', models.CharField(choices=[('pedido', 'Pedido / Venda'), ('servico', 'Serviço Avulso'), ('adiantamento', 'Adiantamento'), ('parcela', 'Parcela'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido')], default='pendente', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='gestao.cliente')),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
    ]
