# Generated by Django 4.2.29 on 2026-03-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_contareceber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('total_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_saida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='meta_mensal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meta mensal de faturamento em R$', max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='taxa_credito',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Taxa do cartão de crédito em % (ex: 3.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaobordado',
            name='taxa_debito',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Taxa do cartão de débito em % (ex: 1.50)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_prevista',
            field=models.DateField(blank=True, help_text='Data prevista de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notificado',
            field=models.BooleanField(default=False, help_text='True quando cliente foi notificado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao_producao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_producao',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('producao', 'Em Produção'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='aguardando', max_length=20),
        ),
        migrations.CreateModel(
            name='LancamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('credito', 'Cartão Crédito'), ('debito', 'Cartão Débito'), ('mix', 'Mix (Múltiplos)'), ('outro', 'Outro')], default='dinheiro', max_length=20)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='gestao.pedido')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
