# Generated by Django 4.2.29 on 2026-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_fechamentocaixa_configuracaobordado_meta_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para notificações de pedido', max_length=254),
        ),
    ]
