# Generated by Django 4.2.29 on 2026-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_cliente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria', 'nome']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='meta_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='taxa_credito',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaobordado',
            name='taxa_debito',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
